version: "3.9"

x-app: &default-app
  build: .
  restart: always

x-env: &env
  env_file:
    - .env

services:
  collab_team:
    <<: [*default-app, *env]
    container_name: collab-team-back
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    <<: *env
    container_name: collab-team-db
    image: postgres:15.3-alpine
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - collab_teampg:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7.0.5-alpine
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD}'
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - collab_team_redis:/data

  worker:
    <<: [*default-app, *env]
    command: ['celery', '--app=core.config.celery:celery', 'worker', '-l', 'info']
    depends_on:
      - collab_team
      - redis

  beat:
    <<: [*default-app, *env]
    command: ['celery', '--app=core.config.celery:celery', 'beat', '-l', 'info']
    depends_on:
      - collab_team
      - redis

  flower:
    <<: *default-app
    command: ['celery', '--broker=${CELERY_BROKER_URL}', 'flower', '--port=5555']
    depends_on:
      - collab_team
      - redis
      - worker
      - beat


volumes:
  collab_teampg:
  collab_team_redis:
