"""user_permissions

Revision ID: c6952d38c131
Revises: f65f255876c0
Create Date: 2023-09-28 16:12:15.244886

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6952d38c131"
down_revision = "2d5f21c387f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_permission",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("codename", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codename"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users_user_permission",
        sa.Column("codename", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["codename"],
            ["users_permission.codename"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_user_permission")
    op.drop_table("users_permission")
    # ### end Alembic commands ###
