"""team models

Revision ID: 438787eee3b8
Revises:
Create Date: 2023-09-16 19:46:13.814309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "438787eee3b8"
down_revision = "cc818e85f637"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams_team",
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("about", sa.String(length=1000), nullable=True),
        sa.Column("owner_uuid", sa.UUID(), nullable=False),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams_team_tool",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams_link_group",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("team_uuid", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_uuid"],
            ["teams_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams_team_tool_group",
        sa.Column("team_uuid", sa.UUID(), nullable=False),
        sa.Column("team_tool_uuid", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_tool_uuid"],
            ["teams_team_tool.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_uuid"],
            ["teams_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teams_team_tool_group")
    op.drop_table("teams_link_group")
    op.drop_table("teams_team_tool")
    op.drop_table("teams_team")
    # ### end Alembic commands ###
