"""boards

Revision ID: a0fcb63800b2
Revises: cc818e85f637
Create Date: 2023-09-17 20:14:07.992389

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0fcb63800b2"
down_revision = "438787eee3b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards_board",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boards_board_owner"), "boards_board", ["owner"], unique=False)
    op.create_table(
        "boards_board_column",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards_board.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boards_label",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards_board.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "boards_card",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("creater_id", sa.UUID(), nullable=False),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deadline_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["boards_board_column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creater_id"],
            ["users_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boards_card_column_id"), "boards_card", ["column_id"], unique=False)
    op.create_index(op.f("ix_boards_card_creater_id"), "boards_card", ["creater_id"], unique=False)
    op.create_table(
        "boards_card_include",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["boards_card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boards_card_label",
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["boards_card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["boards_label.id"],
        ),
        sa.PrimaryKeyConstraint("label_id", "card_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boards_card_label")
    op.drop_table("boards_card_include")
    op.drop_index(op.f("ix_boards_card_creater_id"), table_name="boards_card")
    op.drop_index(op.f("ix_boards_card_column_id"), table_name="boards_card")
    op.drop_table("boards_card")
    op.drop_table("boards_label")
    op.drop_table("boards_board_column")
    op.drop_index(op.f("ix_boards_board_owner"), table_name="boards_board")
    op.drop_table("boards_board")
    # ### end Alembic commands ###
